apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-stage
resources:
  - ../../base/shop-api
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: shop-api
