apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  values:
    architecture: replication
    auth:
      enabled: true
      password: "ChangeMe-Redis-Pass-123"
    master:
      persistence:
        enabled: true
        size: 1Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    replica:
      replicaCount: 2
      persistence:
        enabled: true
        size: 1Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    metrics:
      enabled: false
