apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  chart:
    spec:
      chart: redis-cluster
      version: "11.x.x"
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: docker.io
      repository: bitnamilegacy/redis-cluster
    architecture: null
    auth: null
    master: null
    replica: null
    cluster:
      nodes: 6
      replicas: 1
    usePassword: true
    password: "ChangeMe-Redis-Pass-123"
    persistence:
      enabled: true
      size: 1Gi
    redis:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    metrics:
      enabled: false
