apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop-prod
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patches/postgres-cluster.yaml
    target:
      kind: Cluster
      name: shop-postgres
  - path: patches/redis.yaml
    target:
      kind: HelmRelease
      name: redis
  - path: patches/certificate.yaml
    target:
      kind: Certificate
      name: shop-api-tls
