"""use token since

Revision ID: 7e9020ca0e9c
Revises: c3070afc4785
Create Date: 2025-12-07 17:43:38.997518

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9020ca0e9c"
down_revision: Union[str, Sequence[str], None] = "c3070afc4785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("use_token_since", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_token_since")
    # ### end Alembic commands ###
