"""add password hash

Revision ID: d126ddb48bf6
Revises: a94764a21fd9
Create Date: 2025-12-04 17:06:55.595416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd126ddb48bf6'
down_revision: Union[str, Sequence[str], None] = 'a94764a21fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_password_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_password_key'), 'users', ['password'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
