"""permissions

Revision ID: c3070afc4785
Revises: 9473476667e8
Create Date: 2025-12-06 14:12:15.194272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3070afc4785"
down_revision: Union[str, Sequence[str], None] = "9473476667e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "permissions",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{CAN_SELF_DELETE}'::text[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
