apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shop-postgres
spec:
  instances: 1
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 768Mi
  postgresql:
    parameters:
      max_connections: "75"
      shared_buffers: "96MB"
