apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shop-postgres
spec:
  instances: 1
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
