apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shop-api
spec:
  values:
    image:
      tag: "latest"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    ingress:
      hosts:
        - host: app.local
          paths:
            - path: /api
              pathType: Prefix
            - path: /
              pathType: Prefix
      tls:
        - secretName: shop-api-tls
          hosts:
            - app.local
    config:
      DEBUG: "false"
      PGHOST: "shop-postgres-rw.shop-prod.svc.cluster.local"
      REDIS_HOST: "redis-master.shop-prod.svc.cluster.local"
      BETTER_STACK_URL: "https://in.logs.betterstack.com"
